services:
  - type: web
    name: fastapi-backend
    env: python
    region: oregon  # or "frankfurt" depending on your user base
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    plan: free
    branch: main
    autoDeploy: true
